import type { Theme } from "@openuidev/react-ui";

// Shared palette and typography for the built-in shell and generated responses.
export const responseTheme = {
  "background": "#ffffff",
  "foreground": "#ffffff",
  "popoverBackground": "#ffffff",
  "sunkLight": "#fafafa",
  "sunk": "#f7f7f8",
  "sunkDeep": "#ececec",
  "elevatedLight": "#f7f7f8",
  "elevated": "#ffffff",
  "elevatedStrong": "#e7e7e7",
  "elevatedIntense": "#cecece",
  "overlay": "rgb(0 0 0 / 40%)",
  "highlightSubtle": "#fafafa",
  "highlight": "#f7f7f8",
  "highlightStrong": "#eeeeef",
  "highlightIntense": "#e3e3e3",
  "invertedBackground": "#0d0d0d",
  "textNeutralPrimary": "#0d0d0d",
  "textNeutralSecondary": "#676767",
  "textNeutralTertiary": "#8f8f8f",
  "textNeutralLink": "#0d0d0d",
  "textBrand": "#0d0d0d",
  "textAccentPrimary": "#ffffff",
  "textAccentSecondary": "#dadada",
  "textAccentTertiary": "#b4b4b4",
  "interactiveAccentDefault": "#0d0d0d",
  "interactiveAccentHover": "#2f2f2f",
  "interactiveAccentDisabled": "#b4b4b4",
  "interactiveAccentPressed": "#454545",
  "borderDefault": "#e7e7e7",
  "borderInteractive": "#cecece",
  "borderInteractiveEmphasis": "#8f8f8f",
  "borderInteractiveSelected": "#0d0d0d",
  "borderAccent": "#0d0d0d",
  "borderAccentEmphasis": "#8f8f8f",
  "infoBackground": "#edf5ff",
  "successBackground": "#edf9f2",
  "alertBackground": "#fff8e7",
  "dangerBackground": "#fff0ee",
  "purpleBackground": "#f4f0ff",
  "pinkBackground": "#fff0f6",
  "textInfoPrimary": "#0068bc",
  "textSuccessPrimary": "#00805d",
  "textAlertPrimary": "#946200",
  "textDangerPrimary": "#c1322c",
  "textPurplePrimary": "#7040c1",
  "textPinkPrimary": "#b7377c",
  "borderInfoEmphasis": "#0285ff",
  "borderSuccessEmphasis": "#008764",
  "borderAlertEmphasis": "#e2ab23",
  "borderDangerEmphasis": "#e02e2a",
  "fontBody": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "fontHeading": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "fontLabel": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "fontNumbers": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "fontWeightRegular": "400",
  "fontWeightMedium": "500",
  "fontWeightBold": "600",
  "fontWeightHeavy": "600",
  "textBodyXs": "400 12px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textBodyXsHeavy": "500 12px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textBodySm": "400 14px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textBodySmHeavy": "500 14px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textBodyDefault": "400 16px/1.6 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textBodyDefaultHeavy": "500 16px/1.6 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textBodyLg": "400 18px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textBodyLgHeavy": "500 18px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textHeadingXs": "600 16px/1.4 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textHeadingSm": "600 18px/1.4 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textHeadingMd": "600 22px/1.3 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textHeadingLg": "600 26px/1.25 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textHeadingXl": "600 30px/1.2 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textHeadingMdLetterSpacing": "-0.4px",
  "textHeadingLgLetterSpacing": "-0.6px",
  "textHeadingXlLetterSpacing": "-0.7px",
  "textLabelXs": "400 12px/1.4 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textLabelXsHeavy": "500 12px/1.4 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textLabelSm": "400 14px/1.4 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textLabelSmHeavy": "500 14px/1.4 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textLabelDefault": "400 15px/1.4 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textLabelDefaultHeavy": "500 15px/1.4 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textLabelLg": "400 18px/1.4 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textLabelLgHeavy": "500 18px/1.4 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersXs": "400 12px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersXsHeavy": "500 12px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersSm": "400 14px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersSmHeavy": "500 14px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersDefault": "400 16px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersDefaultHeavy": "500 16px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersLg": "400 18px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersLgHeavy": "500 18px/1.5 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersHeadingSm": "500 18px/1.3 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersHeadingMd": "500 24px/1.2 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersHeadingLg": "500 28px/1.2 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "textNumbersHeadingXl": "500 32px/1.2 -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
  "radiusS": "6px",
  "radiusM": "8px",
  "radiusL": "10px",
  "radiusXl": "12px",
  "radius2xl": "14px",
  "radius3xl": "16px",
  "radius4xl": "20px",
  "radius5xl": "24px",
  "shadowS": "none",
  "shadowM": "none",
  "shadowL": "0 2px 8px rgb(0 0 0 / 4%)",
  "shadowXl": "0 4px 20px rgb(0 0 0 / 6%)",
  "shadow2xl": "0 8px 32px rgb(0 0 0 / 10%)",
  "shadow3xl": "0 16px 48px rgb(0 0 0 / 12%)",
  "chatUserResponseBg": "#f4f4f4",
  "chatUserResponseText": "#0d0d0d"
} satisfies Theme;
