import { chromium } from "playwright-core";
import fs from "fs";
const OUT = process.argv[2] || "frames";
const PROMPT = "I'm in San Francisco for a day, plan a sightseeing route for me";
fs.rmSync(OUT, { recursive: true, force: true }); fs.mkdirSync(OUT);
const browser = await chromium.connectOverCDP("http://localhost:29229");
const ctx = browser.contexts()[0];
const page = await ctx.newPage();
const cdp = await ctx.newCDPSession(page);
await cdp.send("Emulation.setDeviceMetricsOverride", { width: 430, height: 932, deviceScaleFactor: 2, mobile: false });
await page.addInitScript(() => { globalThis[Symbol.for("openui.devtools.autoMount")] = true; });
await page.goto("http://localhost:3000", { waitUntil: "networkidle" });
await page.waitForTimeout(1500);
const log = [];
let n = 0, recording = false;
cdp.on("Page.screencastFrame", async (f) => {
  cdp.send("Page.screencastFrameAck", { sessionId: f.sessionId }).catch(() => {});
  if (!recording) return;
  const name = `${OUT}/f${String(n++).padStart(5, "0")}.jpg`;
  fs.writeFileSync(name, Buffer.from(f.data, "base64"));
  log.push([name, f.metadata.timestamp]);
});
await cdp.send("Page.startScreencast", { format: "jpeg", quality: 92, everyNthFrame: 1 });
const t0 = Date.now();
const mark = (m) => { log.push(["#" + m, Date.now() / 1000]); console.log(m, ((Date.now() - t0) / 1000).toFixed(2)); };
recording = true;
// keep frames flowing even when the page is static
const tick = setInterval(() => page.evaluate(() => { document.body.dataset.t = Date.now(); }).catch(() => {}), 50);
await page.waitForTimeout(800);
const box = page.locator("textarea").first();
await box.click();
await box.pressSequentially(PROMPT, { delay: 28 });
await page.waitForTimeout(300);
mark("send");
await page.keyboard.press("Enter");
await page.waitForSelector(".rt-root", { timeout: 60000 }); mark("first-ui");
await page.waitForSelector(".rt-map-wrap", { timeout: 60000 }); mark("map");
let last = "", stable = 0;
while (stable < 2) { await page.waitForTimeout(300); const h = await page.evaluate(() => document.querySelector(".rt-root")?.innerHTML.length ?? 0); if (h === last && h > 0 && await page.locator(".rt-sugg-wrap").count()) stable++; else stable = 0; last = h; }
mark("done");
const scrollTo = async (sel, idx = 0, wait = 1100, block = "start") => { await page.evaluate(([sel, idx, block]) => document.querySelectorAll(sel)[idx]?.scrollIntoView({ behavior: "smooth", block }), [sel, idx, block]); await page.waitForTimeout(wait); };
await scrollTo(".rt-map-wrap", 0, 900);
await page.click(".rt-expand"); await page.waitForTimeout(1400); mark("expanded");
await page.click(".rt-expand"); await page.waitForTimeout(700);
const cards = await page.locator(".rt-card").count();
for (let i = 0; i < cards; i++) await scrollTo(".rt-card", i, 1000);
mark("cards");
await scrollTo(".rt-sugg-wrap", 0, 1300, "center"); mark("suggestions");
const btn = page.locator(".rt-add").first();
const bb = await btn.boundingBox();
const cx = bb.x + bb.width / 2, cy = bb.y + bb.height / 2;
fs.writeFileSync(`${OUT}/tap.json`, JSON.stringify({ cx, cy }));
await page.evaluate(() => {
  const f = document.createElement("div"); f.id = "finger";
  f.style.cssText = "position:fixed;left:330px;top:820px;width:44px;height:44px;margin:-22px 0 0 -22px;border-radius:50%;background:rgba(40,40,40,.28);border:2px solid rgba(255,255,255,.95);box-shadow:0 2px 10px rgba(0,0,0,.25);z-index:99999;pointer-events:none;opacity:0;transition:left .8s cubic-bezier(.3,.7,.3,1),top .8s cubic-bezier(.3,.7,.3,1),opacity .3s,transform .15s";
  document.body.appendChild(f);
});
mark("finger-in");
await page.evaluate(([x, y]) => { const f = document.getElementById("finger"); f.style.opacity = "1"; requestAnimationFrame(() => { f.style.left = x + "px"; f.style.top = y + "px"; }); }, [cx, cy]);
await page.waitForTimeout(1300);
await page.evaluate(([x, y]) => {
  const f = document.getElementById("finger"); f.style.transform = "scale(.75)";
  const r = document.createElement("div");
  r.style.cssText = `position:fixed;left:${x}px;top:${y}px;width:44px;height:44px;margin:-22px 0 0 -22px;border-radius:50%;border:3px solid rgba(37,99,235,.8);z-index:99998;pointer-events:none;transition:transform .6s ease-out,opacity .6s ease-out`;
  document.body.appendChild(r); requestAnimationFrame(() => { r.style.transform = "scale(2.6)"; r.style.opacity = "0"; });
  setTimeout(() => { f.style.transform = "scale(1)"; }, 180);
}, [cx, cy]);
await page.waitForTimeout(120);
await btn.click(); mark("added");
await page.waitForTimeout(900);
await page.evaluate(() => { document.getElementById("finger").style.opacity = "0"; });
await page.waitForTimeout(500); mark("scroll-map");
await page.waitForTimeout(3400); mark("map-after-add");
await page.screenshot({ path: `${OUT}/../shot_added.png` });
await scrollTo(".rt-card-new", 0, 2800, "center"); mark("new-card");
recording = false; clearInterval(tick);
await cdp.send("Page.stopScreencast");
fs.writeFileSync(`${OUT}/log.json`, JSON.stringify(log));
await page.close();
process.exit(0);
